import type { Expedition, ResearchAsset, GeneratedContent, AuditLog, PolarStation } from '../types/domain';

export const MOCK_STATIONS: PolarStation[] = [
  {
    id: 'maitri',
    name: 'Maitri Research Station',
    region: 'Antarctic',
    established: 1989,
    coordinates: '70°45′57″S 11°44′09″E',
    location_name: 'Schirmacher Oasis, Queen Maud Land',
    operational_status: 'Active',
    description: 'India’s second continental research station in Antarctica, operating year-round for glaciology, atmospheric sciences, geomagnetism, and meteorology.',
  },
  {
    id: 'bharati',
    name: 'Bharati Research Station',
    region: 'Antarctic',
    established: 2012,
    coordinates: '69°24′28″S 76°11′14″E',
    location_name: 'Larsemann Hills, East Antarctica',
    operational_status: 'Active',
    description: 'A state-of-the-art green building research station facilitating deep ice-core studies, oceanography, and continental break-up research with high-speed satellite telemetry.',
  },
  {
    id: 'himadri',
    name: 'Himadri Research Station',
    region: 'Arctic',
    established: 2008,
    coordinates: '78°55′N 11°56′E',
    location_name: 'Ny-Ålesund, Spitsbergen, Svalbard (Norway)',
    operational_status: 'Active',
    description: 'India’s permanent Arctic research base situated at 79° North, focused on atmospheric dynamics, fjord oceanography, Arctic aerosol characterization, and glaciomicrobial ecology.',
  },
  {
    id: 'himansh',
    name: 'Himansh Research Station',
    region: 'Himalayas',
    established: 2016,
    coordinates: '32°24′N 77°37′E (altitude: 4,080 m)',
    location_name: 'Chandra Basin, Lahaul-Spiti, Himachal Pradesh',
    operational_status: 'Active',
    description: 'High-altitude research facility monitoring the third pole cryosphere, glacier mass balance, discharge dynamics, and snow-albedo feedback in the western Himalayas.',
  },
];

export const MOCK_EXPEDITIONS: Expedition[] = [
  {
    id: 'exp-43-isea',
    title: '43rd Indian Scientific Expedition to Antarctica (ISEA-43)',
    region: 'Antarctic',
    start_date: '2023-11-15',
    end_date: '2024-03-30',
    station: 'Maitri & Bharati',
    status: 'Completed',
    asset_count: 14,
    description: 'Comprehensive multidisciplinary polar expedition focusing on ice-sheet radar sounding, Southern Ocean atmospheric profiling, and polar microbial genomic sampling across Queen Maud Land.',
    created_at: '2023-10-01T08:00:00Z',
  },
  {
    id: 'exp-44-isea',
    title: '44th Indian Scientific Expedition to Antarctica (ISEA-44)',
    region: 'Antarctic',
    start_date: '2024-11-10',
    end_date: null,
    station: 'Bharati',
    status: 'Ongoing',
    asset_count: 8,
    description: 'Active polar expedition conducting deep sub-ice drilling at Larsemann Hills, continuous cosmic ray monitoring, and long-term permafrost temperature logging.',
    created_at: '2024-10-15T09:30:00Z',
  },
  {
    id: 'exp-arctic-2024',
    title: 'Indian Arctic Scientific Campaign — Kongsfjorden Survey',
    region: 'Arctic',
    start_date: '2024-06-12',
    end_date: '2024-09-05',
    station: 'Himadri',
    status: 'Completed',
    asset_count: 11,
    description: 'Investigating marine ecosystem responses to Atlantification of Kongsfjorden, trace metal flux from glacier melt runoff, and Black Carbon deposition on Arctic snow cover.',
    created_at: '2024-05-10T11:00:00Z',
  },
  {
    id: 'exp-himalaya-2024',
    title: 'Chandra-Bhaga Glaciological Monitoring Campaign',
    region: 'Himalayas',
    start_date: '2024-07-01',
    end_date: '2024-10-15',
    station: 'Himansh',
    status: 'Completed',
    asset_count: 9,
    description: 'High-elevation glaciological survey measuring seasonal mass balance, glacier velocity with UAV photogrammetry, and glacial lake outburst flood (GLOF) hazard mapping in Lahaul-Spiti.',
    created_at: '2024-06-15T08:00:00Z',
  },
  {
    id: 'exp-soe-12',
    title: '12th Indian Southern Ocean Expedition (SOE-12)',
    region: 'Southern Ocean',
    start_date: '2024-01-08',
    end_date: '2024-02-28',
    station: 'ORV Sagar Nidhi',
    status: 'Completed',
    asset_count: 16,
    description: 'Deep-ocean hydrographic transects across the Subtropical Front and Polar Front down to 65°S, assessing oceanic carbon sequestration, krill acoustic biomass, and ocean acidification.',
    created_at: '2023-12-01T10:00:00Z',
  },
];

export const MOCK_ASSETS: ResearchAsset[] = [
  {
    id: 'asset-001',
    title: 'Ice Sheet Dynamics and Bedrock Topography in Central Dronning Maud Land',
    description: 'Ground penetrating radar (GPR) and seismic reflection sounding data over the polar plateau quantifying ice velocity vectors and subglacial bedrock elevation.',
    asset_type: 'report',
    file_path: 'reports/isea43_central_dml_icesheet.pdf',
    file_size_bytes: 18456200,
    mime_type: 'application/pdf',
    expedition_id: 'exp-43-isea',
    uploaded_by: 'res-01',
    is_public: true,
    is_immutable: true,
    created_at: '2024-04-12T10:15:00Z',
  },
  {
    id: 'asset-002',
    title: 'High-Resolution Black Carbon and Atmospheric Aerosol Measurements at Himadri',
    description: 'Continuous 7-wavelength Aethalometer and scanning mobility particle sizer (SMPS) dataset recorded during the spring-summer transition in Ny-Ålesund, Svalbard.',
    asset_type: 'dataset',
    file_path: 'datasets/arctic_black_carbon_2024_smps.csv',
    file_size_bytes: 45200100,
    mime_type: 'text/csv',
    expedition_id: 'exp-arctic-2024',
    uploaded_by: 'res-02',
    is_public: true,
    is_immutable: true,
    created_at: '2024-09-18T14:30:00Z',
  },
  {
    id: 'asset-003',
    title: 'Glacier Mass Balance and Velocity Profile of Chhota Shigri Glacier',
    description: 'Glaciological stake measurements, snow-pit density profiles, and differential GPS velocity surveys tracking negative mass balance trends over Western Himalayas.',
    asset_type: 'publication',
    file_path: 'publications/chhota_shigri_mass_balance_2024.pdf',
    file_size_bytes: 8920400,
    mime_type: 'application/pdf',
    expedition_id: 'exp-himalaya-2024',
    uploaded_by: 'res-03',
    is_public: true,
    is_immutable: true,
    created_at: '2024-10-22T09:45:00Z',
  },
  {
    id: 'asset-004',
    title: 'Physical Oceanography and Carbon Uptake across Southern Ocean Fronts',
    description: 'CTD-Rosette hydrographic profiles down to 4000m measuring dissolved inorganic carbon (DIC), total alkalinity, and nutrient ratios along the 57°30′E meridian.',
    asset_type: 'dataset',
    file_path: 'datasets/soe12_ctd_carbon_flux.nc',
    file_size_bytes: 98450120,
    mime_type: 'application/x-netcdf',
    expedition_id: 'exp-soe-12',
    uploaded_by: 'res-04',
    is_public: true,
    is_immutable: false,
    created_at: '2024-03-15T16:00:00Z',
  },
  {
    id: 'asset-005',
    title: 'High-Altitude Aerial Photogrammetry & Glacier Front Retreat Imagery',
    description: 'Orthorectified high-resolution drone imagery capturing terminal crevasse formations and moraine-dammed lake expansion in Lahaul-Spiti valley.',
    asset_type: 'photo',
    file_path: 'media/himalayas_batal_drone_ortho.jpg',
    file_size_bytes: 14200500,
    mime_type: 'image/jpeg',
    expedition_id: 'exp-himalaya-2024',
    uploaded_by: 'res-03',
    is_public: true,
    is_immutable: false,
    created_at: '2024-08-10T12:00:00Z',
  },
  {
    id: 'asset-006',
    title: 'Deep Continental Borehole Core Extraction at Larsemann Hills',
    description: 'Operational video and audio documentation of fast-electromechanical diamond core drilling into Antarctic Precambrian basement rock near Bharati Station.',
    asset_type: 'video',
    file_path: 'media/bharati_drilling_exp44.mp4',
    file_size_bytes: 185000000,
    mime_type: 'video/mp4',
    expedition_id: 'exp-44-isea',
    uploaded_by: 'res-01',
    is_public: true,
    is_immutable: false,
    created_at: '2024-12-05T08:20:00Z',
  },
  {
    id: 'asset-007',
    title: 'Cryoconite Hole Bacterial Communities and Metagenomic Diversity in Svalbard',
    description: 'Metagenomic DNA sequencing of cold-adapted psychrophilic cyanobacteria and microeukaryotes sampled from glacier meltwater ponds in Kongsfjorden.',
    asset_type: 'publication',
    file_path: 'publications/arctic_cryoconite_metagenomics.pdf',
    file_size_bytes: 6500000,
    mime_type: 'application/pdf',
    expedition_id: 'exp-arctic-2024',
    uploaded_by: 'res-02',
    is_public: true,
    is_immutable: true,
    created_at: '2024-10-01T15:10:00Z',
  },
  {
    id: 'asset-008',
    title: 'Prydz Bay Antarctic Krill Acoustic Density Biomass Survey',
    description: 'Calibrated dual-frequency (38 & 120 kHz) SIMRAD EK80 echosounder echograms tracking Euphausia superba swarming depth and diurnal vertical migration.',
    asset_type: 'dataset',
    file_path: 'datasets/prydz_bay_krill_acoustics_2024.csv',
    file_size_bytes: 32400100,
    mime_type: 'text/csv',
    expedition_id: 'exp-soe-12',
    uploaded_by: 'res-04',
    is_public: true,
    is_immutable: false,
    created_at: '2024-03-28T11:45:00Z',
  },
];

export const MOCK_GENERATED_CONTENT: GeneratedContent[] = [
  {
    id: 'content-001',
    asset_id: 'asset-001',
    content_type: 'article',
    title: 'Echoes Through the Ice: Mapping the Subglacial Valleys Beneath Antarctica',
    body: `Deep underneath two kilometers of ancient Antarctic ice sheet lies a rugged continental landscape of jagged mountain peaks, deep canyons, and hidden river valleys. During the 43rd Indian Scientific Expedition to Antarctica (ISEA-43), NCPOR glaciologists deployed cutting-edge Ground Penetrating Radar (GPR) along a 400-kilometer overland traverse from Maitri Station into the Queen Maud Land interior.\n\nBy transmitting high-frequency electromagnetic pulses through the crystalline ice and recording the returning echoes from the ice-bedrock boundary, researchers constructed the most detailed three-dimensional subglacial topography map of this sector to date. The soundings revealed a previously uncharted subglacial trench over 600 meters deep, which acts as a primary channel guiding inland ice flow toward the coast.\n\nUnderstanding this sub-ice bedrock topography is pivotal for global climate models. When bed friction is low, ice streams can accelerate rapidly into the ocean, directly impacting global sea levels. The team's findings provide baseline data for predicting how East Antarctica’s massive ice sheet will respond to ongoing atmospheric and oceanic warming over the next century.`,
    tags: ['Antarctica', 'Glaciology', 'Radar Sounding', 'Ice Sheet Dynamics', 'Climate Modeling', 'ISEA-43'],
    status: 'published',
    published_at: '2024-05-10T12:00:00Z',
    created_at: '2024-04-14T11:00:00Z',
  },
  {
    id: 'content-002',
    asset_id: 'asset-001',
    content_type: 'summary',
    title: 'Executive Summary: ISEA-43 Bedrock Sounding',
    body: `Summary of findings from ground-penetrating radar profiling across Queen Maud Land during ISEA-43: (1) Identified a 600m deep subglacial trench accelerating ice stream movement; (2) Measured mean ice thickness varying between 1,450m and 2,320m; (3) Refined geothermal heat flux constraints needed for Antarctic ice sheet numerical models.`,
    tags: ['Antarctica', 'Executive Summary', 'GPR', 'Ice Velocity'],
    status: 'published',
    published_at: '2024-05-10T12:05:00Z',
    created_at: '2024-04-14T11:05:00Z',
  },
  {
    id: 'content-003',
    asset_id: 'asset-002',
    content_type: 'article',
    title: 'Soot in the Snow: Unraveling Arctic Aerosols from India’s Himadri Station',
    body: `High above the Arctic Circle in the international science village of Ny-Ålesund, Svalbard, India’s Himadri Research Station monitors the quiet arrival of industrial pollutants carried thousands of miles from temperate continents.\n\nBlack Carbon (BC)—microscopic particles emitted from incomplete combustion of fossil fuels and boreal forest fires—absorbs solar radiation in the atmosphere and, once deposited on white snow and sea ice, darkens the reflective surface. This reduced albedo accelerates melting, creating a positive feedback loop known as Arctic Amplification.\n\nNCPOR researchers analyzed seasonal variations in aerosol size distribution and equivalent Black Carbon concentrations. The measurements confirmed significant spring pulse events ('Arctic Haze') transported via circumpolar winds, while summer showed localized biological aerosol emissions. These insights are directly assisting international Arctic Council working groups in assessing long-range transport mitigation treaties.`,
    tags: ['Arctic', 'Atmospheric Sciences', 'Himadri Station', 'Black Carbon', 'Albedo Feedback', 'Svalbard'],
    status: 'published',
    published_at: '2024-10-02T10:00:00Z',
    created_at: '2024-09-20T16:00:00Z',
  },
  {
    id: 'content-004',
    asset_id: 'asset-003',
    content_type: 'article',
    title: 'Vanishing Towers: How Himalayan Glaciers Regulate Water for Millions',
    body: `Often termed the 'Third Pole', the Himalayas hold the largest volume of snow and ice outside the polar regions, serving as the headwaters for Asia’s major river systems. From the high-altitude Himansh Research Station at 4,080 meters in Chandra Basin, NCPOR glaciologists have tracked the health of benchmark glaciers including Chhota Shigri and Batal.\n\nThe 2024 comprehensive campaign recorded an accelerated negative mass balance rate of -0.85 meters water equivalent per year, coupled with ice flow velocities slowing down as the glacier thins. Crucially, the data reveals significant enlargement of supraglacial and proglacial lakes held back by fragile moraines, underscoring urgent monitoring needed for Glacial Lake Outburst Floods (GLOFs) threatening downstream communities.`,
    tags: ['Himalayas', 'Himansh', 'Glacier Retreat', 'Third Pole', 'Water Security', 'GLOF Hazard'],
    status: 'published',
    published_at: '2024-11-05T09:00:00Z',
    created_at: '2024-10-25T14:30:00Z',
  },
  {
    id: 'content-005',
    asset_id: 'asset-004',
    content_type: 'article',
    title: 'The Great Southern Ocean Sink: How Roaring Forties Trap Anthropogenic Carbon',
    body: `The tempestuous Southern Ocean encircling Antarctica is the planet’s most potent marine carbon sink, drawing down roughly 40% of all ocean-absorbed anthropogenic CO2. Aboard research vessel ORV Sagar Nidhi, Indian scientists navigated heavy seas across the Roaring Forties and Furious Fifties to quantify this vital planetary service.\n\nUsing deep-sea CTD rosettes down to abyssal depths of 4,000 meters, researchers measured seawater pH, dissolved inorganic carbon, and nitrate-to-silicate ratios. The newly released dataset shows that vigorous wind-driven upwelling and subsequent deep water formation are carrying captured atmospheric carbon into the deep ocean for multi-century storage, although slight acidification is beginning to stress calcareous marine microplankton at the base of the food web.`,
    tags: ['Southern Ocean', 'Oceanography', 'Carbon Sink', 'Ocean Acidification', 'ORV Sagar Nidhi'],
    status: 'admin_approved',
    published_at: null,
    created_at: '2024-03-20T11:00:00Z',
  },
  {
    id: 'content-006',
    asset_id: 'asset-007',
    content_type: 'article',
    title: 'Microscopic Titans: Cold-Adapted Microbes Surviving Arctic Glacial Cryoconite',
    body: `Drifting on Arctic glaciers, cryoconite holes are water-filled melt pits lined with dark biological dust. Within these miniature ecological sanctuaries at sub-zero temperatures, specialized microbial life thrives. Recent genomic sequencing from Himadri reveals novel psychrophilic enzymes that function optimally in extreme cold, opening vast opportunities for green biotechnology and astrobiology research.`,
    tags: ['Arctic', 'Microbiology', 'Cryoconite', 'Biotechnology', 'Himadri'],
    status: 'peer_review',
    published_at: null,
    created_at: '2024-10-05T08:00:00Z',
  },
  {
    id: 'content-007',
    asset_id: 'asset-006',
    content_type: 'article',
    title: 'Deep Drilling Operations in Larsemann Hills for Paleoclimate Clues',
    body: `Draft report on the mechanical core drilling operations near Bharati Station in East Antarctica. Core samples recovered from 180 meters depth represent sedimentary sequences spanning several glacial-interglacial cycles. Currently under peer review before public release.`,
    tags: ['Antarctica', 'Bharati', 'Core Drilling', 'Paleoclimate'],
    status: 'draft',
    published_at: null,
    created_at: '2024-12-08T10:00:00Z',
  },
  {
    id: 'content-008',
    asset_id: 'asset-005',
    content_type: 'social_x',
    title: 'Drone Survey in Lahaul-Spiti — X Thread',
    body: `🧊 UAV Drone photogrammetry in Chandra Basin reveals 12% moraine expansion over 3 seasons. High-resolution orthomosaics generated by NCPOR's #Himansh station allow millimeter-scale tracking of glacier crevasse widening. #PolarScience #Glaciology #IndiaInHimalayas`,
    tags: ['Himalayas', 'Drone', 'SocialMedia'],
    status: 'draft',
    published_at: null,
    created_at: '2024-08-12T15:00:00Z',
  },
  {
    id: 'content-009',
    asset_id: 'asset-008',
    content_type: 'article',
    title: 'Unverified Acoustic Survey Summary of Prydz Bay',
    body: `Initial unprocessed echogram interpretation draft. Marked for revision due to missing calibration coefficients for 120kHz beam spread.`,
    tags: ['Southern Ocean', 'Krill', 'Draft'],
    status: 'rejected',
    published_at: null,
    created_at: '2024-04-01T09:00:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 101,
    actor_id: 'usr-admin-01',
    actor_name: 'Dr. Anand Sharma (Admin)',
    action: 'publish_article',
    entity: 'generated_content',
    entity_id: 'content-001',
    metadata: { title: 'Echoes Through the Ice', prev_status: 'admin_approved', new_status: 'published' },
    created_at: '2024-05-10T12:00:00Z',
  },
  {
    id: 102,
    actor_id: 'usr-editor-01',
    actor_name: 'Priya Narayanan (Editor)',
    action: 'approve_peer_review',
    entity: 'generated_content',
    entity_id: 'content-005',
    metadata: { title: 'The Great Southern Ocean Sink', prev_status: 'peer_review', new_status: 'admin_approved' },
    created_at: '2024-03-20T11:00:00Z',
  },
  {
    id: 103,
    actor_id: 'usr-res-01',
    actor_name: 'Dr. Rajesh Patel (Researcher)',
    action: 'process_document',
    entity: 'research_assets',
    entity_id: 'asset-001',
    metadata: { filename: 'isea43_central_dml_icesheet.pdf', pages_read: 18, llm_model: 'llama3' },
    created_at: '2024-04-14T10:45:00Z',
  },
  {
    id: 104,
    actor_id: 'usr-admin-01',
    actor_name: 'Dr. Anand Sharma (Admin)',
    action: 'set_asset_immutable',
    entity: 'research_assets',
    entity_id: 'asset-001',
    metadata: { is_immutable: true, reason: 'Official scientific report published' },
    created_at: '2024-05-10T12:05:00Z',
  },
  {
    id: 105,
    actor_id: 'usr-editor-01',
    actor_name: 'Priya Narayanan (Editor)',
    action: 'reject_draft',
    entity: 'generated_content',
    entity_id: 'content-009',
    metadata: { reason: 'Missing calibration coefficients in data table' },
    created_at: '2024-04-02T14:15:00Z',
  },
];
